name: Build Images
'on':
  schedule:
  - cron: 28 0 * * *
  pull_request_target: null
  push:
    branches:
    - main
    - v[0-9]+-[0-9]+-test
permissions:
  contents: read
env:
  MOUNT_SELECTED_LOCAL_SOURCES: 'false'
  FORCE_ANSWER_TO_QUESTIONS: 'yes'
  FORCE_PULL_IMAGES: 'false'
  CHECK_IMAGE_FOR_REBUILD: 'true'
  SKIP_CHECK_REMOTE_IMAGE: 'true'
  DB_RESET: 'true'
  VERBOSE: 'true'
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_USERNAME: ${{ github.actor }}
  CONSTRAINTS_GITHUB_REPOSITORY: "${{ secrets.CONSTRAINTS_GITHUB_REPOSITORY != ''\
    \ &&\n    secrets.CONSTRAINTS_GITHUB_REPOSITORY || 'apache/airflow' }}"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REGISTRY_PULL_IMAGE_TAG: latest
  GITHUB_REGISTRY_WAIT_FOR_IMAGE: 'false'
  INSTALL_PROVIDERS_FROM_SOURCES: 'true'
  AIRFLOW_LOGIN_TO_GITHUB_REGISTRY: 'true'
  GITHUB_REGISTRY_PUSH_IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha
    }}
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build-info:
    timeout-minutes: 10
    name: Build Info
    runs-on: ubuntu-latest
    env:
      targetBranch: ${{ github.event.pull_request.base.ref }}
      pullRequestLabels: ${{ toJSON(github.event.pull_request.labels.*.name) }}
    outputs:
      runsOn: ${{ github.repository == 'apache/airflow' && '["self-hosted"]' || '["ubuntu-20.04"]'
        }}
      pythonVersions: ${{ steps.selective-checks.python-versions }}
      upgradeToNewerDependencies: ${{ steps.selective-checks.outputs.upgrade-to-newer-dependencies
        }}
      allPythonVersions: ${{ steps.selective-checks.outputs.all-python-versions }}
      defaultPythonVersion: ${{ steps.selective-checks.outputs.default-python-version
        }}
      run-tests: ${{ steps.selective-checks.outputs.run-tests }}
      run-kubernetes-tests: ${{ steps.selective-checks.outputs.run-kubernetes-tests
        }}
      image-build: ${{ steps.dynamic-outputs.outputs.image-build }}
      cacheDirective: ${{ steps.dynamic-outputs.outputs.cacheDirective }}
      targetBranch: ${{ steps.dynamic-outputs.outputs.targetBranch }}
      defaultBranch: ${{ steps.selective-checks.outputs.default-branch }}
      targetCommitSha: ${{steps.discover-pr-merge-commit.outputs.targetCommitSha ||
        github.event.pull_request.head.sha || github.sha }}
    steps:
    - name: Discover PR merge commit
      id: discover-pr-merge-commit
      run: 'TARGET_COMMIT_SHA="$(gh api ''${{ github.event.pull_request.url }}'' --jq
        .merge_commit_sha)"

        echo "TARGET_COMMIT_SHA=$TARGET_COMMIT_SHA" >> $GITHUB_ENV

        echo "::set-output name=targetCommitSha::${TARGET_COMMIT_SHA}"

        '
      if: github.event_name == 'pull_request_target'
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.TARGET_COMMIT_SHA }}
        persist-credentials: false
        fetch-depth: 2
    - name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: recursive
    - name: env
      run: printenv
      env:
        dynamicOutputs: ${{ toJSON(steps.dynamic-outputs.outputs) }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Selective checks
      id: selective-checks
      env:
        PR_LABELS: ${{ env.pullRequestLabels }}
      run: "if [[ ${GITHUB_EVENT_NAME} == \"pull_request_target\" ]]; then\n  # Run\
        \ selective checks\n  ./scripts/ci/selective_ci_checks.sh \"${TARGET_COMMIT_SHA}\"\
        \nelse\n  # Run all checks\n  ./scripts/ci/selective_ci_checks.sh\nfi\n"
    - name: Compute dynamic outputs
      id: dynamic-outputs
      run: "set -x\nif [[ \"${{ github.event_name }}\" == 'pull_request_target' ]];\
        \ then\n    echo \"::set-output name=targetBranch::${targetBranch}\"\nelse\n\
        \  # Direct push to branch, or scheduled build\n    echo \"::set-output name=targetBranch::${GITHUB_REF#refs/heads/}\"\
        \nfi\n\nif [[ \"${{ github.event_name }}\" == 'schedule' ]]; then\n    echo\
        \ \"::set-output name=cacheDirective::disabled\"\nelse\n    echo \"::set-output\
        \ name=cacheDirective::pulled\"\nfi\n\nif [[ \"$SELECTIVE_CHECKS_IMAGE_BUILD\"\
        \ == \"true\" && \"$BUILD_IMAGES_OVERRIDE\" != \"false\" ]]; then\n    echo\
        \ \"::set-output name=image-build::true\"\nelse\n    echo \"::set-output name=image-build::false\"\
        \nfi\n"
      env:
        SELECTIVE_CHECKS_IMAGE_BUILD: ${{ steps.selective-checks.outputs.image-build
          }}
        BUILD_IMAGES_OVERRIDE: ${{ secrets.AIRFLOW_GITHUB_REGISTRY_WAIT_FOR_IMAGE
          }}
  build-ci-images:
    permissions:
      packages: write
    timeout-minutes: 80
    name: Build CI images ${{matrix.python-version}}
    runs-on: ${{ fromJson(needs.build-info.outputs.runsOn) }}
    needs:
    - build-info
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.build-info.outputs.allPythonVersions) }}
      fail-fast: true
    if: needs.build-info.outputs.image-build == 'true'
    env:
      RUNS_ON: ${{ fromJson(needs.build-info.outputs.runsOn)[0] }}
      BACKEND: postgres
      PYTHON_MAJOR_MINOR_VERSION: ${{ matrix.python-version }}
      UPGRADE_TO_NEWER_DEPENDENCIES: ${{ needs.build-info.outputs.upgradeToNewerDependencies
        }}
      DOCKER_CACHE: ${{ needs.build-info.outputs.cacheDirective }}
      CHECK_IF_BASE_PYTHON_IMAGE_UPDATED: '${{ github.event_name == ''pull_request_target''
        && ''false'' || ''true'' }}

        '
      outputs: ${{toJSON(needs.build-info.outputs) }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ needs.build-info.outputs.targetCommitSha }}
        persist-credentials: false
        submodules: recursive
    - name: Retrieve DEFAULTS from the _initialization.sh
      id: defaults
      run: "DEFAULT_BRANCH=$(grep \"export DEFAULT_BRANCH\" scripts/ci/libraries/_initialization.sh\
        \ | \\\n  awk 'BEGIN{FS=\"=\"} {print $3}' | sed s'/[\"}]//g')\necho \"DEFAULT_BRANCH=${DEFAULT_BRANCH}\"\
        \ >> $GITHUB_ENV\nDEFAULT_CONSTRAINTS_BRANCH=$(grep \"export DEFAULT_CONSTRAINTS_BRANCH\"\
        \ \\\n  scripts/ci/libraries/_initialization.sh | \\\n  awk 'BEGIN{FS=\"=\"\
        } {print $3}' | sed s'/[\"}]//g')\necho \"DEFAULT_CONSTRAINTS_BRANCH=${DEFAULT_CONSTRAINTS_BRANCH}\"\
        \ >> $GITHUB_ENV\n"
    - name: 'Checkout "${{ needs.build-info.outputs.targetBranch }}" branch to ''main-airflow''
        folder to use ci/scripts from there.

        '
      uses: actions/checkout@v2
      with:
        path: main-airflow
        ref: ${{ needs.build-info.outputs.targetBranch }}
        persist-credentials: false
        submodules: recursive
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ needs.build-info.outputs.defaultPythonVersion }}
    - name: 'Override "scripts/ci" with the "${{ needs.build-info.outputs.targetBranch
        }}" branch so that the PR does not override it

        '
      run: 'rm -rf "scripts/ci"

        mv "main-airflow/scripts/ci" "scripts"

        '
    - name: Free space
      run: ./scripts/ci/tools/free_space.sh
    - name: Build CI images ${{ matrix.python-version }}:${{ env.GITHUB_REGISTRY_PUSH_IMAGE_TAG
        }}
      run: ./scripts/ci/images/ci_prepare_ci_image_on_ci.sh
    - name: Push CI images ${{ matrix.python-version }}:${{ env.GITHUB_REGISTRY_PUSH_IMAGE_TAG
        }}
      run: ./scripts/ci/images/ci_push_ci_images.sh
  build-prod-images:
    permissions:
      packages: write
    timeout-minutes: 80
    name: Build PROD images ${{matrix.python-version}}
    runs-on: ${{ fromJson(needs.build-info.outputs.runsOn) }}
    needs:
    - build-info
    - build-ci-images
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.build-info.outputs.allPythonVersions) }}
      fail-fast: true
    if: needs.build-info.outputs.image-build == 'true'
    env:
      RUNS_ON: ${{ fromJson(needs.build-info.outputs.runsOn)[0] }}
      BACKEND: postgres
      PYTHON_MAJOR_MINOR_VERSION: ${{ matrix.python-version }}
      UPGRADE_TO_NEWER_DEPENDENCIES: ${{ needs.build-info.outputs.upgradeToNewerDependencies
        }}
      DOCKER_CACHE: ${{ needs.build-info.outputs.cacheDirective }}
      CHECK_IF_BASE_PYTHON_IMAGE_UPDATED: '${{ github.event_name == ''pull_request_target''
        && ''false'' || ''true'' }}

        '
      VERSION_SUFFIX_FOR_PYPI: .dev0
      INSTALL_PROVIDERS_FROM_SOURCES: '${{ needs.build-info.outputs.defaultBranch
        == ''main'' && ''true'' || ''false'' }}

        '
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ needs.build-info.outputs.targetCommitSha }}
        persist-credentials: false
        submodules: recursive
    - name: Retrieve DEFAULTS from the _initialization.sh
      id: defaults
      run: "DEFAULT_BRANCH=$(grep \"export DEFAULT_BRANCH\" scripts/ci/libraries/_initialization.sh\
        \ | \\\n  awk 'BEGIN{FS=\"=\"} {print $3}' | sed s'/[\"}]//g')\necho \"DEFAULT_BRANCH=${DEFAULT_BRANCH}\"\
        \ >> $GITHUB_ENV\nDEFAULT_CONSTRAINTS_BRANCH=$(grep \"export DEFAULT_CONSTRAINTS_BRANCH\"\
        \ \\\n  scripts/ci/libraries/_initialization.sh | \\\n  awk 'BEGIN{FS=\"=\"\
        } {print $3}' | sed s'/[\"}]//g')\necho \"DEFAULT_CONSTRAINTS_BRANCH=${DEFAULT_CONSTRAINTS_BRANCH}\"\
        \ >> $GITHUB_ENV\n"
    - name: 'Checkout "${{ needs.build-info.outputs.targetBranch }}" branch to ''main-airflow''
        folder to use ci/scripts from there.

        '
      uses: actions/checkout@v2
      with:
        path: main-airflow
        ref: ${{ needs.build-info.outputs.targetBranch }}
        persist-credentials: false
        submodules: recursive
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ needs.build-info.outputs.defaultPythonVersion }}
    - name: 'Override "scripts/ci" with the "${{ needs.build-info.outputs.targetBranch
        }}" branch so that the PR does not override it

        '
      run: 'rm -rf "scripts/ci"

        mv "main-airflow/scripts/ci" "scripts"

        '
    - name: Free space
      run: ./scripts/ci/tools/free_space.sh
    - name: Build CI images ${{ matrix.python-version }}:${{ env.GITHUB_REGISTRY_PUSH_IMAGE_TAG
        }}
      run: ./scripts/ci/images/ci_prepare_ci_image_on_ci.sh
      env:
        GITHUB_REGISTRY_WAIT_FOR_IMAGE: 'true'
    - name: Build PROD images ${{ matrix.python-version }}:${{ env.GITHUB_REGISTRY_PUSH_IMAGE_TAG
        }}
      run: ./scripts/ci/images/ci_prepare_prod_image_on_ci.sh
      env:
        GITHUB_REGISTRY_PULL_IMAGE_TAG: latest
    - name: Push PROD images ${{ matrix.python-version }}:${{ env.GITHUB_REGISTRY_PUSH_IMAGE_TAG
        }}
      run: ./scripts/ci/images/ci_push_production_images.sh
      env:
        GITHUB_REGISTRY_PULL_IMAGE_TAG: latest
  cancel-on-ci-build:
    permissions:
      actions: write
    name: Cancel `Tests` jobs on workflow failed/cancelled
    runs-on: ubuntu-latest
    if: failure() || cancelled()
    needs:
    - build-ci-images
    - build-prod-images
    env:
      branch: ${{ github.event.pull_request.head.ref }}
      thisRun: ${{ github.run_id }}
    steps:
    - name: Find running `Tests` jobs for ${{ env.GITHUB_REGISTRY_PUSH_IMAGE_TAG }}
      run: "if [[ \"${{ github.event_name }}\" == 'pull_request_target' ]]; then\n\
        \  event_filter=\"event=pull_request&\"\nelse\n  branch=\"${GITHUB_REF#refs/heads/}\"\
        \n  event_filter=\"\"\nfi\n\nfor cancel_url in $(\n    gh api \"/repos/$GITHUB_REPOSITORY/actions/runs?${event_filter}branch=${branch}\"\
        \ \\\n        jq -r '\n          .workflow_runs[] |\n          select(.head_sha\
        \ == $ENV.GITHUB_REGISTRY_PUSH_IMAGE_TAG and .status != \"completed\") |\n\
        \          .cancel_url\n        ' \\\n); do\n  # One of these URls will be\
        \ _this_ workflow, so lets exclude that!\n  [[ $cancel_url  == */$thisRun/*\
        \ ]] && continue\n\n  echo \"Cancelling $cancel_url\"\n  gh api -X POST --silent\
        \ \"$cancel_url\"\ndone\n"
